name: quraan_pulaar
description: A Pulaar translation of the Holy Quran
publish_to: 'none'
version: 2.6.9

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  just_audio: ^0.9.36
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  audio_session: ^0.1.18
  collection: ^1.18.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/data/surahs.json
    - assets/audio/
    - assets/fonts/
    - assets/icon/
    - assets/icons/
    - assets/images/
    - assets/animations/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "store_assets/ios/icon/original.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "store_assets/ios/icon/original.png"
